export const GETCOMPANIES = 'GETCOMPANIES';
export const GETMYFAVORITECOMPANIES = 'GETMYFAVORITECOMPANIES';
export const MARKASFAVORITE = 'MARKASFAVORITE';
export const UNMARKASFAVORITE = 'UNMARKASFAVORITE';
export const ERRORS = 'ERRORS';
